version: '3.9'
services:
  api:
    image: ghcr.io/rodrigovcortezi/csinfo-api
    build:
      context: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
      - db-data:/app/prisma/data
      - /app/node_modules
  redis:
    image: 'redis:alpine'
    volumes:
      - redis-data:/data
  retriever:
    depends_on:
      - api
      - redis
    image: ghcr.io/rodrigovcortezi/csinfo-retriever
    build:
      context: ./retriever
    volumes:
      - ./retriever:/app
      - /app/node_modules
  bot:
    depends_on:
      - api
      - redis
    image: ghcr.io/rodrigovcortezi/csinfo-bot
    build:
      context: ./bot
    volumes:
      - ./bot:/app
      - /app/node_modules
    environment:
      - APP_KEY
      - APP_SECRET
      - ACCESS_TOKEN
      - ACCESS_SECRET
    command: node index.js
volumes:
  db-data:
    driver: local
  redis-data:
    driver: local
