name: Build and Deploy

on:
  push:
    branches: main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        run: |
          docker-compose build
          docker-compose push
  deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Pull image and restart
        uses: appleboy/ssh-action@master
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER: ${{ github.actor }}
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: TOKEN,USER
          script: |
            cd /home/ec2-user/csinfo
            git fetch --all
            git reset --hard origin/main
            git pull origin main
            docker-compose down
            echo $TOKEN | docker login ghcr.io -u ${USER} --password-stdin
            docker-compose pull
            docker-compose up -d
            docker system prune -f
