name: Build and Deploy

on:
  push:
    branches: main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        run: |
          docker-compose build
          docker-compose push
  deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Pull image and restart
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          USER_NAME: ${{ secrets.USER_NAME}}
        run: |
          echo $PRIVATE_KEY > key.pem && chmod 400 key.pem
          echo key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${USER_NAME}@${HOSTNAME} '
            cd /home/ec2-user/csinfo
            echo "${{ secrets.GITHUB_TOKEN }}" > jorge
          '
